name: Scheduled Visibility Change

on:
  schedule:
    - cron: "31 6 30 6 *"  # 30th June at 06:31 UTC = 12:01 PM IST
  workflow_dispatch:  # Optional: allow manual run

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Change Repo to Public
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"private": false}'
